# Generated by Django 5.2.7 on 2025-12-11 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author (API)',
                'verbose_name_plural': 'Authors (API)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('fiction', 'Художественная литература'), ('textbook', 'Учебник'), ('science', 'Научная литература'), ('business', 'Бизнес-литература'), ('other', 'Другое')], default='fiction', max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('is_textbook', models.BooleanField(default=False)),
                ('edition', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_api.authorapi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book (API)',
                'verbose_name_plural': 'Books (API)',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title', 'author', 'publication_year', 'publisher'), name='unique_book_api')],
            },
        ),
    ]
